# Generated by Django 4.1.5 on 2023-01-23 19:51

from django.db import migrations, models
import djongo.models.fields
import testgen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True)),
                ('test_id', models.IntegerField(db_index=True)),
                ('_id', models.UUIDField()),
                ('questions', djongo.models.fields.ArrayField(model_container=testgen.models.GeneratedQuestion)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
