# Generated by Django 4.1.5 on 2023-01-23 20:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionNonAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(blank=True)),
                ('question_id', models.IntegerField()),
                ('answers', djongo.models.fields.JSONField(default={})),
                ('given_answer', djongo.models.fields.JSONField(blank=True)),
            ],
        ),
    ]
