version: '3.8'
services:
  backend:
    build:
      context: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - mongodb
  db:
    container_name: pg_database
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 54323:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  mongodb:
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongodb/data/db

volumes:
  postgres_data:
  pgadmin-data:
  mongo: