# Generated by Django 4.1.5 on 2023-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ques', models.TextField(verbose_name='Question')),
                ('img_ques', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/d/ques', verbose_name='Image')),
                ('is_sel_quest', models.BooleanField(default=True)),
                ('score', models.SmallIntegerField(default=1)),
                ('position_in_test', models.IntegerField(default=-1)),
                ('answer_var_n', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ans', models.CharField(max_length=255, verbose_name='Answers')),
                ('explanation', models.TextField(blank=True)),
                ('img_ans', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/d/ans', verbose_name='image')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('info', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('n_quest', models.IntegerField()),
                ('is_positional', models.BooleanField(default=False)),
                ('duration', models.DurationField(default='01:00:00')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='category_tests', to='testcreater.category')),
            ],
        ),
    ]
