# Generated by Django 4.1.7 on 2023-02-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcreater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinggroup",
            name="group_members",
            field=models.ManyToManyField(
                blank=True, related_name="member_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="testinggroup",
            name="group_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="testinggroup",
            name="group_tests",
            field=models.ManyToManyField(
                blank=True, related_name="in_groups", to="testcreater.test"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="category_tests",
                to="testcreater.category",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="testcreater.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="testcreater.test",
            ),
        ),
    ]
