# Generated by Django 4.1.5 on 2023-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcreater', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='category_tests', to='testcreater.category'),
        ),
        migrations.DeleteModel(
            name='TestListAPIView',
        ),
    ]
