# Generated by Django 4.1.5 on 2023-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcreater', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='n_quest',
            field=models.IntegerField(null=True),
        ),
    ]
