# Generated by Django 4.1.5 on 2023-01-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcreater', '0003_alter_category_title_alter_test_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_ques',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/d/ques', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='img_ans',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/d/ans', verbose_name='image'),
        ),
    ]
