# Generated by Django 4.1.6 on 2023-02-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingGroup',
        ),
    ]
