# Generated by Django 4.1.5 on 2023-01-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcreater', '0004_alter_question_img_ques_alter_questionanswer_img_ans'),
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinggroup',
            name='group_tests',
            field=models.ManyToManyField(blank=True, related_name='in_groups', to='testcreater.test'),
        ),
    ]
